version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      babel:
        patterns:
          - "@babel/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-config-*"
          - "eslint-plugin-*"
      patternfly:
        patterns:
          - "@patternfly/*"
      react:
        patterns:
          - "react"
          - "react-dom"
      redhat:
        patterns:
          - "@redhat-cloud-services/*"
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-redux'
        update-types: ['version-update:semver-major']
      - dependency-name: 'redux'
        update-types: ['version-update:semver-major']
      - dependency-name: 'redux-thunk'
        update-types: ['version-update:semver-major']
      - dependency-name: 'sass'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
